version: '3'
services:
  cassandra-node1:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: cassandra-node1
    environment:
      NODE_NAME: "Node1"
      PEER_ADDRESS: "cassandra-node2:50051"
    ports:
      - "50051:50051"
    networks:
      - cassandra-net

  cassandra-node2:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: cassandra-node2
    environment:
      NODE_NAME: "Node2"
      PEER_ADDRESS: "cassandra-node1:50051"
    ports:
      - "50052:50051"
    networks:
      - cassandra-net

networks:
  cassandra-net:
    driver: bridge